name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      # Report both platforms. z1 cares about the BSD/GNU split.
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get update && sudo apt-get install -y zsh bats parallel
        if: ${{ runner.os == 'Linux' }}
      - run: brew install bats-core parallel
        if: ${{ runner.os == 'macOS' }}
      - run: ./tests/run
